Repository jitacm/30-days-C-Bank_Account, pull requests merged in 2025-08, with the labels that each got.

#10 Feature 2 of Issue Number: #8
  bank_system.c
Labels: bug, 30daysdevchallenge, jitacm, level-1

#14 Add Money Transfer Between Accounts Feature
  bank_system.c
Labels: 30daysdevchallenge, jitacm, feature, level-3

#18 Feature 5 of Issue Number: #8
  bank_system.c
Labels: 30daysdevchallenge, jitacm, feature, level-3

#23 Major Documentation Overhaul — Secure Banking CLI Guide Added #22
  Readme.md
Labels: documentation, 30daysdevchallenge, jitacm, level-2

#27 Bug Fixes for Transfer and Delete Logic
  admin.dat
  bank_system.c
  bank_system.exe
Labels: bug, 30daysdevchallenge, jitacm, level-2

#31 New Features: Transaction History and Admin Controls
  bank_system.c
  bank_system.exe
Labels: 30daysdevchallenge, jitacm, feature, level-3

#35 Adds Loan Application and Status Tracking Feature
  bank_system.c
  bank_system.exe
Labels: 30daysdevchallenge, jitacm, feature, level-4

#45 Adds Multi-Currency Support
  bank_system.c
Labels: 30daysdevchallenge, jitacm, feature, level-3
